
package multi_agent_project_2019;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


public class TwitterFrame extends javax.swing.JFrame {

    /**
     * Creates new form TwitterFrame
     */
    public TwitterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btn_send_tweet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_recievers_names = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_area_tweets = new javax.swing.JTextArea();
        btn_clear_tweets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("tweet Content:");

        btn_send_tweet.setText("Send tweet");

        jLabel2.setText("Send to:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tweets:");

        text_area_tweets.setColumns(20);
        text_area_tweets.setRows(5);
        jScrollPane2.setRowHeaderView(text_area_tweets);

        btn_clear_tweets.setText("Clear Tweets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jLabel1)
        							.addGap(115))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(combo_recievers_names, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        					.addGap(158))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(btn_send_tweet, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(44)
        					.addComponent(jLabel3))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(35)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btn_clear_tweets, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(combo_recievers_names, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(34)
        					.addComponent(btn_send_tweet))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btn_clear_tweets)))
        			.addGap(44))
        );
        text_area_tweet_content = new javax.swing.JTextArea();
        jScrollPane1.setViewportView(text_area_tweet_content);
        
                text_area_tweet_content.setColumns(20);
                text_area_tweet_content.setRows(5);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public javax.swing.JButton getBtn_clear_mtweets() {
		return btn_clear_tweets;
	}
    public javax.swing.JButton getBtn_send_tweets() {
		return btn_send_tweet;
	}
    public javax.swing.JTextArea getText_area_tweet_content() {
		return text_area_tweet_content;
	}
    public javax.swing.JTextArea getText_area_tweets() {
		return text_area_tweets;
	}
    public javax.swing.JComboBox<String> getCombo_recievers_names() {
		return combo_recievers_names;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear_tweets;
    private javax.swing.JButton btn_send_tweet;
    private javax.swing.JComboBox<String> combo_recievers_names;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea text_area_tweet_content;
    private javax.swing.JTextArea text_area_tweets;
    // End of variables declaration//GEN-END:variables
}
